ALTER TABLE `2026_Participants`
    ADD COLUMN `Undertaking` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `CertificateIssued` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `Attendance` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `PrizeMoneySent` TINYINT(1) NOT NULL DEFAULT 0;
